simplepages/urls.py
from django.urls import path
from .views import home, PageView

app_name = 'simplepages'
urlpatterns = [
    path('', home, name="page-home"),
    path('<slug:slug>', PageView.as_view(), name='page-view'),
]

users/urls.py
from django.urls import path
from .views import LoginView, RegisterView

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name="users-login"),
    path('register', RegisterView.as_view(), name="users-register"),
]

webapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = 'Django Server Manager'
admin.site.site_title = 'Django Server Manager Administration'

urlpatterns = [
    path('admin/', admin.site.urls), # Admin Django
    path('', include("simplepages.urls")), # Module: SimplePages
    path('users/', include("users.urls")), # Module: SimplePages

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

simplepages/models.py
from django.db import models
from django.urls import reverse

class Page (models.Model):

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)


    def get_absolute_url(self):
        return reverse('page-view', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
        

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import models as auth_models
from datetime import date

class UserManager(auth_models.BaseUserManager):
  
    def create_user(self, username, first_name, 
                        last_name, dob, email, password):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email))
        user.first_name = first_name
        user.last_name = last_name
        user.dob = dob
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, first_name, 
                        last_name, dob, email, password ) :

        user = self.create_user(username=username, first_name=first_name, 
                                last_name=last_name, dob=dob, 
                                email=email, password=password)

        user.is_superuser = user.is_staff = True
        user.save(using=self._db)
        return user

class User(AbstractUser):
    dob = models.DateField(
        _('date of birth')
    )
    email = models.EmailField(
		_('email address'),
		unique=True,
		blank=True
	)
    cellphone = models.CharField(
		_('cell phone'),
		max_length=20,
		null=True, blank=True
	)

    objects = UserManager()

    REQUIRED_FIELDS = ['first_name', 'last_name', 'email', 'dob']

    class Meta:
        verbose_name = 'Organizer / Participant'
        verbose_name_plural = 'Organizers / Participants'
        ordering = ('id', )

    def get_age(self):
        today = date.today()
        return today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))

    def __unicode__(self):
        return u'{0} ({1})'.format(self.get_full_name(), self.email)

    def get_short_name(self):
        return self.first_name

    def get_full_name(self):
        return u'{0} {1}'.format(self.first_name, self.last_name)

web_hosting/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Project (models.Model):
    STATUS_APP = (
        ('Run', 'Run'),
        ('Deploying', 'Deploying'),
        ('Deploying_Fail', 'Deploying Failed'),
        ('Stop', 'Stop'),
    )
    STATUS_GITHUB = (
        ('Fail', 'Fail'),
        ('Ok', 'Ok'),
    )
    domain = models.CharField(max_length=120, unique=True)
    projectname = models.SlugField(max_length=30, unique=True)
    git_url = models.URLField(_("git url"), max_length=255)
    git_token = models.CharField(_("git token access"), max_length=255)
    updated_on = models.DateTimeField(auto_now= True)
    created_on = models.DateTimeField(auto_now_add=True)
    status_app = models.CharField(choices=STATUS_APP, max_length=30, editable=False)
    status_github = models.CharField(choices=STATUS_GITHUB, max_length=30, editable=False)
    
    class Meta:
        ordering = ['-domain']

    def __str__(self):
        return self.domain

users/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from .models import User


class UserCreationForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput,
                                help_text="Enter the same password as above, for verification.")

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = auth_forms.ReadOnlyPasswordHashField(label="Password",
        help_text="Raw passwords are not stored, so there is no way to see "
                  "this user's password, but you can change the password "
                  "using <a href=\"password/\">this form</a>.")

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        return self.initial["password"]

web_hosting/forms.py
from django import forms
from .models import Project

class AddProjectForm(forms.ModelForm):
    error_messages = {
        'domain_taken': "domain is taken",
        'projectname_taken' : "projectname is taken",
    }

        
    class Meta:
        model = Project
        fields = ('domain', 'projectname', 'git_url', 'git_token' )

    def save(self, commit=True):
        instance = super(AddProjectForm, self).save(commit=False)
        CreateInstance = AgentClass()
        CreateInstance.CreateProject(instance)
        return instance

simplepages/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Page


def home(request):
    return render(request, "public_home.html")

class PageView(DetailView):
    model = Page
    template_name = 'page.html'

users/views.py
from django.views.generic.base import TemplateView

class LoginView(TemplateView):

    template_name = "users/login.html"

class RegisterView(TemplateView):

    template_name = "users/register.html"

web_hosting/views.py
from django.shortcuts import render

# Create your views here.

simplepages/templates/home.html
{% extends "template/base.html" %} {% block title %} Home {% endblock %} {% block content %} 
{% load static %} 
  <!-- Masthead -->
  <header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">Build a landing page for your business or project and generate more leads!</h1>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
          <form>
            <div class="form-row">
              <div class="col-12 col-md-9 mb-2 mb-md-0">
                <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
              </div>
              <div class="col-12 col-md-3">
                <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </header>

  <!-- Icons Grid -->
  <section class="features-icons bg-light text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-screen-desktop m-auto text-primary"></i>
            </div>
            <h3>Fully Responsive</h3>
            <p class="lead mb-0">This theme will look great on any device, no matter the size!</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-layers m-auto text-primary"></i>
            </div>
            <h3>Bootstrap 4 Ready</h3>
            <p class="lead mb-0">Featuring the latest build of the new Bootstrap 4 framework!</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-check m-auto text-primary"></i>
            </div>
            <h3>Easy to Use</h3>
            <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Image Showcases -->
  <section class="showcase">
    <div class="container-fluid p-0">
      <div class="row no-gutters">

        <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static '/home/img/bg-showcase-1.jpg' %}');"></div>
        <div class="col-lg-6 order-lg-1 my-auto showcase-text">
          <h2>Fully Responsive Design</h2>
          <p class="lead mb-0">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>
        </div>
      </div>
      <div class="row no-gutters">
        <div class="col-lg-6 text-white showcase-img" style="background-image: url('{% static '/home/img/bg-showcase-2.jpg' %}');"></div>
        <div class="col-lg-6 my-auto showcase-text">
          <h2>Updated For Bootstrap 4</h2>
          <p class="lead mb-0">Newly improved, and full of great utility classes, Bootstrap 4 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 4!</p>
        </div>
      </div>
      <div class="row no-gutters">
        <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static '/home/img/bg-showcase-3.jpg' %}');"></div>
        <div class="col-lg-6 order-lg-1 my-auto showcase-text">
          <h2>Easy to Use &amp; Customize</h2>
          <p class="lead mb-0">Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Testimonials -->
  <section class="testimonials text-center bg-light">
    <div class="container">
      <h2 class="mb-5">What people are saying...</h2>
      <div class="row">
        <div class="col-lg-4">
          <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/testimonials-1.jpg' %}" alt="">
            <h5>Margaret E.</h5>
            <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/testimonials-2.jpg' %}" alt="">
            <h5>Fred S.</h5>
            <p class="font-weight-light mb-0">"Bootstrap is amazing. I've been using it to create lots of super nice landing pages."</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/testimonials-3.jpg' %}" alt="">
            <h5>Sarah W.</h5>
            <p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Call to Action -->
  <section class="call-to-action text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h2 class="mb-4">Ready to get started? Sign up now!</h2>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
          <form>
            <div class="form-row">
              <div class="col-12 col-md-9 mb-2 mb-md-0">
                <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
              </div>
              <div class="col-12 col-md-3">
                <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>



{% endblock %}

simplepages/templates/page.html
{% extends "template/base.html" %} {% block title %} {{ object.title }} {% endblock %}
{% load static %} 

{% block content %}


<div class="row d-flex justify-content-center">

  <!--Grid column-->
  <div class="col-md-10">
    <h1 class="text-center">{{ object.title }}</h1>
    <hr>
    <p>{{ object.content }}</p>
  </div>
  <!--Grid column-->

</div>


{% endblock %}

simplepages/templates/public_home.html
{% extends "template/base_public.html" %} {% block title %} Home {% endblock %} {% block content %} 
{% load static %} 
<div class="container">
   <h1 class="text-center">Hi!<div class="eo eo-sunglasses"></div></h1>

</div>


{% endblock %}

users/templates/users/login.html
{% extends "template/base.html" %} {% block title %} Login {% endblock %}
{% load static %} 

{% block content %}
<div class="mt-5">
<div class="row d-flex justify-content-center">
    <h1>Login</h1>
</div>


<div class="row d-flex justify-content-center">

  <!--Grid column-->
  <div class="col-md-3 mt-3 mb-3">
    <div class="card">
        <article class="card-body">
            <a href="{%url 'users:users-register'%}" class="float-right btn btn-outline-primary">Sign up</a>
            <h4 class="card-title mb-4 mt-1">Sign in</h4>
            <p>
                <a href="" class="btn btn-block btn-outline-info"> <i class="fab fa-twitter"></i>   Login via Twitter</a>
                <a href="" class="btn btn-block btn-outline-primary"> <i class="fab fa-facebook-f"></i>   Login via facebook</a>
            </p>
            <hr>
            <form>
            <div class="form-group">
                <input name="" class="form-control" placeholder="Email or login" type="email">
            </div> <!-- form-group// -->
            <div class="form-group">
                <input class="form-control" placeholder="Enter your password" type="password">
            </div> <!-- form-group// -->                                      
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                    </div> <!-- form-group// -->
                </div>
                <div class="col-md-6 text-right">
                    <a class="small" href="#">Forgot password?</a>
                </div>                                            
            </div> <!-- .row// -->                                                                  
        </form>
        </article>
        </div>

</div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends "template/base.html" %} {% block title %} Register {% endblock %}
{% load static %} 

{% block content %}
<div class="mt-5">
<div class="row d-flex justify-content-center">
    <h1>Register</h1>
</div>

<div class="row d-flex justify-content-center">


  <!--Grid column-->
  <div class="col-md-5 mt-3 mb-3">
    <div class="card">
        <article class="card-body">
            <div class="container px-1">
                <div class="row">
                    <div class="col-md-10 mx-auto">
                        <form>
                            <div class="form-group row">
                                <div class="col-sm-6">
                                    <label for="inputFirstname">First name</label>
                                    <input type="text" class="form-control" id="inputFirstname" placeholder="First name">
                                </div>
                                <div class="col-sm-6">
                                    <label for="inputLastname">Last name</label>
                                    <input type="text" class="form-control" id="inputLastname" placeholder="Last name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6">
                                    <label for="inputAddressLine1">Address</label>
                                    <input type="text" class="form-control" id="inputAddressLine1" placeholder="Street Address">
                                </div>
                                <div class="col-sm-6">
                                    <label for="inputAddressLine2">Address (Line 2)</label>
                                    <input type="text" class="form-control" id="inputAddressLine2" placeholder="Line 2">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6">
                                    <label for="inputCity">City</label>
                                    <input type="text" class="form-control" id="inputCity" placeholder="City">
                                </div>
                                <div class="col-sm-6">
                                    <label for="inputState">State</label>
                                    <input type="text" class="form-control" id="inputState" placeholder="State">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6">
                                    <label for="inputPostalCode">Postal Code</label>
                                    <input type="text" class="form-control" id="inputPostalCode" placeholder="Postal Code">
                                </div>
                                <div class="col-sm-6">
                                    <label for="inputCity">Country</label>
                                    <input type="text" class="form-control" id="inputCountry" placeholder="Country">
                                </div>
                            </div>                            
                            <div class="row">
                                <div class="col-xs-4 col-sm-3 col-md-3">
                                    <span class="button-checkbox">
                                        <button type="button" class="btn" data-color="info" tabindex="7">I Agree</button>
                                        <input type="checkbox" name="t_and_c" id="t_and_c" class="hidden" value="1">
                                    </span>
                                </div>
                                <div class="col-xs-8 col-sm-9 col-md-9">
                                     By clicking <strong class="label label-primary">Register</strong>, you agree to the <a href="#" data-toggle="modal" data-target="#t_and_c_m">Terms and Conditions</a> set out by this site, including our Cookie Use.
                                </div>
                            </div>
                            <button type="button" class="btn btn-primary px-4 text-center">Save</button>
                        </form>
            
        </article>
        </div>

</div>
</div>

{% endblock %}